CREATE CURSOR vpedidos (PEDIDO C(12), OBS C(100))

APPEND FROM "C:\TEMP\altera_obs2.txt" DELIMITED  WITH CHARACTER ";"
*!*	replace ALL  obs WITH STRTRAN(OBS,"CART√ÉO","CART√O")

*!*	SELECT VPEDIDOS
*!*	SCAN 
*!*		
*!*		F_SELECT("SELECT OBS FROM COMPRAS WHERE PEDIDO = ?VPEDIDOS.PEDIDO","VTMP1")
*!*		MCOBS = ALLTRIM(VTMP1.OBS) + CHR(13)+CHR(10) +ALLTRIM(VPEDIDOS.OBS)
*!*		F_EXECUTE("UPDATE COMPRAS SET OBS = ?MCOBS WHERE PEDIDO = ?VPEDIDOS.PEDIDO")
*!*		
*!*	ENDSCAN
XX=.F.
SCAN 
	IF XX
		f_select(vpedidos.obs,"tmp2")
		F_SELECT("SELECT OBS FROM COMPRAS WHERE PEDIDO = ?VPEDIDOS.PEDIDO","VTMP1")
		MCOBS = ALLTRIM(VTMP1.OBS) + CHR(13)+CHR(10) +"NOVA GRADE DO PEDIDO - CONSIDERAR ESTA:" +CHR(13)+CHR(10)+ALLTRIM(tmp2.descricao_grade)
		F_EXECUTE("UPDATE COMPRAS SET OBS = ?MCOBS WHERE PEDIDO = ?VPEDIDOS.PEDIDO")
	ELSE
		F_SELECT("SELECT OBS FROM COMPRAS WHERE PEDIDO = ?VPEDIDOS.PEDIDO","VTMP1")
		mcobs = VPEDIDOS.PEDIDO + CHR(13)+CHR(10)+ REPLICATE("=",8)+CHR(13)+CHR(10)+ALLTRIM(VTMP1.OBS)+CHR(13)+CHR(10)++CHR(13)+CHR(10)
		STRTOFILE(MCOBS,"C:\TEMP\OBS_PEDIDOS_16DEZ21.TXT",1)
		
	ENDIF
	
ENDSCAN

*!*	browse