CREATE PROCEDURE DBO.CSM_GERA_TRANSF AS


declare @filial_origem varchar(25), @filial_destino varchar(25), @chave_origem varchar(44), @errmsg varchar(255), @emissao datetime, @serie_nf char(2), @ANOMES varchar(6), 
		@TRANSITO VARCHAR(20), @cod_clifor varchar(6), @cnpj varchar(20), @uf_filial char(2), @cidade varchar(40), @matriz_fiscal varchar(25), @cod_filial varchar(6),
		@cfop varchar(10), @uf_destino varchar(2), @valor_total numeric(10,2), @qtde_total int, @PESO_L NUMERIC(10,4), @PESO_B NUMERIC(10,4), @nf_numero varchar(12),
		@CHAVE_NFE varchar(44)


/*
declare @codigo_cliente varchar(25), @rede_loja varchar(14), @SEQUENCIA varchar(10), @valor_total numeric(10,2), @qtde_total int, 
		@filial varchar(25), @romaneio varchar(25), @NOME_CLIFOR  VARCHAR(25), 
		@rateio_cc varchar(40), @clifor varchar(6)
*/


-- INCLUO OS NOVOS CASOS A FILA DE PROCESSAMENTO
INSERT INTO CSM_FILA_TRANSF (CHAVE_DEV, CHAVE_TRANSF, LOG_PROCESSAMENTO)
SELECT DISTINCT ID_NFE_ORIGINAL, NULL, NULL 
FROM CGP_DEVOLUCAO_ECOM A
LEFT JOIN CSM_FILA_TRANSF B ON A.ID_NFE_ORIGINAL = B.CHAVE_DEV
WHERE B.CHAVE_DEV IS NULL


--DEFINO OS PARAMETROS BASICOS DE PROCESSAMENTO
SELECT @ANOMES = RIGHT(CAST(DATEPART(YY,GETDATE()) AS CHAR(4)),2) +                 
CASE WHEN LEN(CAST(DATEPART(MM,GETDATE()) AS CHAR(2))) = 2                 
THEN CAST(DATEPART(MM,GETDATE()) AS CHAR(2))                
ELSE '0' + CAST(DATEPART(MM,GETDATE()) AS CHAR(2)) END   

set @emissao = cast(getdate() as date)

set @serie_nf = '9'

SELECT @TRANSITO = VALOR_ATUAL FROM PARAMETROS WHERE PARAMETRO = 'CSM_TRANSITO_AUTOMATICO'

begin try
	CREATE TABLE #TEMP(CHAVE_NF CHAR(44))
end try
begin catch
end catch


--Varro as notas ainda nao emitidas
DECLARE cur_fila CURSOR LOCAL FAST_FORWARD FOR 
	select chave_dev from CSM_FILA_TRANSF where chave_transf is null
	
OPEN cur_fila 

FETCH NEXT FROM cur_fila INTO @chave_origem

WHILE @@FETCH_STATUS = 0 
BEGIN 
	set @filial_origem = NULL
	set @filial_destino = NULL
	SET @cod_clifor = NULL

	select @filial_origem = b.FILIAL, @cnpj = c.cgc_cpf, @uf_filial = c.uf, @cidade = c.CIDADE, @matriz_fiscal = b.MATRIZ_FISCAL, @cod_filial = b.cod_filial
	from CGP_DEVOLUCAO_ECOM A
	join filiais b on right('0000' +rtrim(ltrim(cod_loja)),4) = substring(b.CGC_CPF, 9, 4)
	join CADASTRO_CLI_FOR c on b.FILIAL = c.NOME_CLIFOR
	where ID_NFE_ORIGINAL = @chave_origem and b.filial = 'LOJA VIRTUAL'

	if @filial_origem is null
	begin
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'FILIAL DE ORIGEM DO FATURAMENTO NAO ENCONTRADA!' WHERE chave_dev = @chave_origem
		GOTO PROXIMO
	END

	select @filial_destino = b.FILIAL, @cod_clifor = B.COD_FILIAL, @uf_destino = c.UF
	from CGP_DEVOLUCAO_ECOM A
	join filiais b on right('0000' +rtrim(ltrim(COD_TROCA)),4) = substring(b.CGC_CPF, 9, 4)
	join CADASTRO_CLI_FOR c on b.FILIAL = c.NOME_CLIFOR
	where ID_NFE_ORIGINAL = @chave_origem

	if @filial_origem is null
	begin
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'FILIAL DE DESTINO DO FATURAMENTO NAO ENCONTRADA!' WHERE chave_dev = @chave_origem
		GOTO PROXIMO
	END

	set @CFOP = case when @UF_DESTINO <> @uf_filial then '6152' else '5152' end

	set @qtde_total = 0
	set @valor_total = 0

	select @qtde_total = sum(quantidade), @valor_total = sum(QUANTIDADE * c.PRECO1), @PESO_L = sum(QUANTIDADE * P.PESO), @PESO_B = sum(QUANTIDADE * P.PESO)
	from CGP_DEVOLUCAO_ECOM a
	left join PRODUTOS_BARRA b on a.COD_MERCADORIA = b.CODIGO_BARRA 
	left join PRODUTOS_PRECOS c on b.produto = c.produto and c.CODIGO_TAB_PRECO = '02'
	LEFT JOIN PRODUTOS P ON B.PRODUTO = P.PRODUTO
	where ID_NFE_ORIGINAL = @chave_origem

	if isnull(@valor_total,0)  = 0 or isnull(@qtde_total,0) = 0
	begin
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'QUANTIDADE OU VALOR DOS ITENS ZERADA!' WHERE chave_dev = @chave_origem
		GOTO PROXIMO
	END

	BEGIN TRANSACTION
	
	--gero a capa
	begin try
		insert into FATURAMENTO
		(
			FILIAL,
			NF_SAIDA,
			SERIE_NF,
			CODIGO_LOCAL_ENTREGA,
			FILIAL_FATURADA,
			TIPO_FATURAMENTO,
			LANCAMENTO,
			NOME_CLIFOR,
			CONDICAO_PGTO,
			NATUREZA_SAIDA,
			TRANSPORTADORA,
			TRANSP_REDESPACHO,
			TIPO_FRETE,
			COD_TRANSACAO,
			EMISSAO,
			DATA_SAIDA,
			FRETE,
			SEGURO,
			DESCONTO,
			DESCONTO_COND_PGTO,
			ENCARGO,
			ICMS,
			IPI_VALOR,
			VALOR_TOTAL,
			QTDE_TOTAL,
			NF_FATURA,
			FATURA,
			NOTA_IMPRESSA,
			ACERTO_CONTAS_P_R,
			TABELA_FILHA,
			OBS,
			PESO_LIQUIDO,
			PESO_BRUTO,
			VOLUMES,
			TIPO_VOLUME,
			CONFERIDO,
			CONFERIDO_POR,
			ENTREGA_CIF,
			IRRF,
			IRRF_RET_FONTE,
			NOTA_CANCELADA,
			DEVOLUCAO,
			REPRESENTANTE,
			COMISSAO,
			PORCENTAGEM_ACERTO,
			GERENTE,
			COMISSAO_GERENTE,
			DESCONTO_BRUTO,
			TIMESTAMP,
			CONFERENCIA,
			MARCA_EXPORTACAO,
			ATUALIZACAO_EXPORTAR,
			DATA_EXPORTACAO,
			ICMS_BASE,
			STATUS_TRANSITO,
			DATA_CANCELAMENTO,
			VALOR_CANCELADO,
			QTDE_CANCELADA,
			MOEDA,
			CAMBIO_NA_DATA,
			COBRAR_MOEDA_PADRAO,
			DATA_FATURAMENTO_RELATIVO,
			RECARGO,
			DATA_PARA_TRANSFERENCIA,
			NOME_CLIFOR_ENTREGA,
			TABELA_PRECO_FRETE,
			VALOR_FRETE,
			NOME_CLIFOR_COBRANCA,
			VALOR_ADICIONAL,
			IPI_ADICIONAL,
			OBS_TRANSPORTE,
			AGRUPAMENTO_ITENS,
			COMISSAO_VALOR,
			COMISSAO_VALOR_GERENTE,
			CTB_ITEM,
			CTB_LANCAMENTO,
			DESCONTO_BRUTO_1,
			DESCONTO_BRUTO_2,
			DESCONTO_BRUTO_3,
			DESCONTO_BRUTO_4,
			DESCONTO_SOBRE_1,
			DESCONTO_SOBRE_2,
			DESCONTO_SOBRE_3,
			DESCONTO_SOBRE_4,
			EMPRESA,
			FATURA_FILIAL,
			FATURA_NUMERO,
			FATURA_SERIE,
			ICMS_ISENTO,
			ICMS_OUTROS,
			MPADRAO_DESCONTO,
			MPADRAO_DESCONTO_COND_PGTO,
			MPADRAO_ENCARGO,
			MPADRAO_FRETE,
			MPADRAO_IMPOSTO_AGREGAR,
			MPADRAO_SEGURO,
			MPADRAO_VALOR_SUB_ITENS,
			MPADRAO_VALOR_TOTAL,
			MULTI_DESCONTO_ACUMULAR,
			NUMERO_CONFERENCIA,
			PORC_DESCONTO,
			PORC_DESCONTO_BRUTO,
			PORC_DESCONTO_COND_PGTO,
			PORC_DESCONTO_DIGITADO,
			PORC_ENCARGO,
			RATEIO_CENTRO_CUSTO,
			RATEIO_FILIAL,
			VALOR_DIFERENCA_GUIA_FATURA,
			VALOR_IMPOSTO_AGREGAR,
			VALOR_SUB_ITENS,
			IMPRIMIR_ENDERECO_COBRANCA,
			INDICA_CONSUMIDOR_FINAL,
			BANCO,
			AGENCIA,
			RESPONSAVEL_TRANSPORTE,
			NOTA_COMPLEMENTAR,
			NUMERO_CONHECIMENTO_RELACIONADO,
			PORC_DESCONTO_SEFAZ,
			DESCONTO_SEFAZ,
			MPADRAO_DESCONTO_SEFAZ,
			ID_CAIXA_PGTO,
			NRO_DE,
			DATA_DE,
			NATUREZA_EXPORTACAO,
			NRO_RE,
			DATA_RE,
			NRO_CONHECIMENTO_EMBARQUE,
			DATA_CONHECIMENTO,
			TIPO_CONHECIMENTO,
			COD_PAIS,
			NRO_COMPROVANTE_EXPORTACAO,
			DATA_COMPROVANTE_EXPORTACAO,
			DATA_AVERBACAO,
			NF_EMITIDA_EXPORTADOR,
			COD_RELACIONAMENTO_RE_NF,
			NF_E_NUMERO,
			NF_E_DATA_EMISSAO,
			NF_E_COD_VERIFICACAO,
			NF_E_DATA_QUITACAO_GUIA,
			NF_E_GERACAO,
			SEQUENCIAL_UNICO,
			DATA_GERACAO_NSU,
			CODIGO_CLIENTE_VAREJO,
			PIN,
			CHAVE_NFE,
			PROTOCOLO_AUTORIZACAO_NFE,
			PROTOCOLO_CANCELAMENTO_NFE,
			DATA_AUTORIZACAO_NFE,
			GERAR_AUTOMATICO,
			STATUS_NFE,
			LOG_STATUS_NFE,
			MOTIVO_CANCELAMENTO_NFE,
			ITEM_NFE,
			PRIORIZACAO,
			REGISTRO_DPEC,
			DATA_REGISTRO_DPEC,
			TIPO_EMISSAO_NFE,
			FIN_EMISSAO_NFE,
			COD_MOTIVO_CANC,
			OBS_INTERESSE_FISCO,
			DATA_CONTINGENCIA,
			JUSTIFICATIVA_CONTINGENCIA,
			UF_EMBARQUE_EXPORTACAO,
			LOCAL_EMBARQUE_EXPORTACAO,
			CFOP_CANCELAMENTO,
			VALOR_DESPACHO,
			VALOR_IMPOSTO_INCIDENCIA,
			MPADRAO_VALOR_IMPOSTO_INCIDENCIA,
			VEICULO_PLACA,
			UF_PLACA_VEICULO,
			INFORMACAO_COMPLEMENTAR,
			MARCA_VOLUMES,
			NUMERACAO_VOLUMES,
			DATA_HORA_EMISSAO,
			INDICA_PRESENCA_COMPRADOR,
			LOCAL_DESPACHO_EXPORTACAO,
			UTC_DATA_AUTORIZACAO_NFE,
			UTC_DATA_SAIDA,
			UTC_EMISSAO,
			INDICA_ENDERECO_ENTREGA,
			CONSTRUCAO_CIVIL,
			CADASTRO_CNO,
			INFO_PGTO,
			TIPO_DOC_EXPORTACAO
		)
		select
			FILIAL = @filial_origem,
			NF_SAIDA = 'T99999',
			SERIE_NF = @serie_nf,
			CODIGO_LOCAL_ENTREGA = NULL,
			FILIAL_FATURADA = NULL,
			TIPO_FATURAMENTO = 'TRANSFERENCIA',
			LANCAMENTO = NULL,
			NOME_CLIFOR = @filial_destino,
			CONDICAO_PGTO = '001',
			NATUREZA_SAIDA = '120.01',
			TRANSPORTADORA = 'NOSSO CARRO',
			TRANSP_REDESPACHO = 'NOSSO CARRO',
			TIPO_FRETE = '01',
			COD_TRANSACAO = 'FATURAMENTO_052',
			EMISSAO = @emissao,
			DATA_SAIDA = @emissao,
			FRETE = 0,
			SEGURO = 0,
			DESCONTO = 0,
			DESCONTO_COND_PGTO = 0,
			ENCARGO = 0,
			ICMS = 0,
			IPI_VALOR = 0,
			VALOR_TOTAL = @valor_total,
			QTDE_TOTAL = @qtde_total,
			NF_FATURA = 0,
			FATURA = NULL,
			NOTA_IMPRESSA = 0,
			ACERTO_CONTAS_P_R = 0,
			TABELA_FILHA = 'FATURAMENTO_PROD',
			OBS = NULL,
			PESO_LIQUIDO = @PESO_L,
			PESO_BRUTO = @PESO_B,
			VOLUMES = @qtde_total,
			TIPO_VOLUME = 'PACK',
			CONFERIDO = 0,
			CONFERIDO_POR = '',
			ENTREGA_CIF = 1,
			IRRF = 0,
			IRRF_RET_FONTE = 0,
			NOTA_CANCELADA = 0,
			DEVOLUCAO = 0,
			REPRESENTANTE = @filial_destino,
			COMISSAO = 0,
			PORCENTAGEM_ACERTO = 0,
			GERENTE = @filial_destino,
			COMISSAO_GERENTE = 0,
			DESCONTO_BRUTO = 0,
			TIMESTAMP = null,
			CONFERENCIA  = null,
			MARCA_EXPORTACAO  = null,
			ATUALIZACAO_EXPORTAR = null,
			DATA_EXPORTACAO  = null,
			ICMS_BASE = 0,
			STATUS_TRANSITO  = null,
			DATA_CANCELAMENTO  = null,
			VALOR_CANCELADO = 0,
			QTDE_CANCELADA = 0,
			MOEDA = 'R$',
			CAMBIO_NA_DATA = 1,
			COBRAR_MOEDA_PADRAO = 1,
			DATA_FATURAMENTO_RELATIVO = null,
			RECARGO = 0,
			DATA_PARA_TRANSFERENCIA = getdate(),
			NOME_CLIFOR_ENTREGA =  @filial_destino,
			TABELA_PRECO_FRETE = '',
			VALOR_FRETE = 0,
			NOME_CLIFOR_COBRANCA = null,
			VALOR_ADICIONAL  = null,
			IPI_ADICIONAL  = null,
			OBS_TRANSPORTE = '',
			AGRUPAMENTO_ITENS = 0,
			COMISSAO_VALOR = 0,
			COMISSAO_VALOR_GERENTE = 0,
			CTB_ITEM = NULL,
			CTB_LANCAMENTO = NULL,
			DESCONTO_BRUTO_1 = 0,
			DESCONTO_BRUTO_2 = 0,
			DESCONTO_BRUTO_3 = 0,
			DESCONTO_BRUTO_4 = 0,
			DESCONTO_SOBRE_1 = 0,
			DESCONTO_SOBRE_2 = 0,
			DESCONTO_SOBRE_3 = 0,
			DESCONTO_SOBRE_4 = 0,
			EMPRESA = 1,
			FATURA_FILIAL = null,
			FATURA_NUMERO = null,
			FATURA_SERIE = null,
			ICMS_ISENTO = 0,
			ICMS_OUTROS = 0,
			MPADRAO_DESCONTO = 0,
			MPADRAO_DESCONTO_COND_PGTO  = 0,
			MPADRAO_ENCARGO  = 0,
			MPADRAO_FRETE  = 0,
			MPADRAO_IMPOSTO_AGREGAR  = 0,
			MPADRAO_SEGURO = 0,
			MPADRAO_VALOR_SUB_ITENS = @valor_total,
			MPADRAO_VALOR_TOTAL =  @valor_total,
			MULTI_DESCONTO_ACUMULAR  = 0,
			NUMERO_CONFERENCIA = null,
			PORC_DESCONTO = 0,
			PORC_DESCONTO_BRUTO = 0,
			PORC_DESCONTO_COND_PGTO = 0,
			PORC_DESCONTO_DIGITADO = 0,
			PORC_ENCARGO = 0,
			RATEIO_CENTRO_CUSTO = null,
			RATEIO_FILIAL  = null,
			VALOR_DIFERENCA_GUIA_FATURA = 0,
			VALOR_IMPOSTO_AGREGAR = 0,
			VALOR_SUB_ITENS = @valor_total,
			IMPRIMIR_ENDERECO_COBRANCA = 0,
			INDICA_CONSUMIDOR_FINAL  = 0,
			BANCO = null,
			AGENCIA  = null,
			RESPONSAVEL_TRANSPORTE  = null,
			NOTA_COMPLEMENTAR = 0,
			NUMERO_CONHECIMENTO_RELACIONADO = null,
			PORC_DESCONTO_SEFAZ = 0,
			DESCONTO_SEFAZ  = 0,
			MPADRAO_DESCONTO_SEFAZ  = 0,
			ID_CAIXA_PGTO = null,
			NRO_DE  = null,
			DATA_DE   = null,
			NATUREZA_EXPORTACAO   = null,
			NRO_RE   = null,
			DATA_RE   = null,
			NRO_CONHECIMENTO_EMBARQUE   = null,
			DATA_CONHECIMENTO   = null,
			TIPO_CONHECIMENTO   = null,
			COD_PAIS   = null,
			NRO_COMPROVANTE_EXPORTACAO   = null,
			DATA_COMPROVANTE_EXPORTACAO   = null,
			DATA_AVERBACAO   = null,
			NF_EMITIDA_EXPORTADOR   = null,
			COD_RELACIONAMENTO_RE_NF   = null,
			NF_E_NUMERO  = null,
			NF_E_DATA_EMISSAO = null,
			NF_E_COD_VERIFICACAO = null,
			NF_E_DATA_QUITACAO_GUIA = null,
			NF_E_GERACAO   = null,
			SEQUENCIAL_UNICO   = null,
			DATA_GERACAO_NSU   = null,
			CODIGO_CLIENTE_VAREJO   = null,
			PIN   = null,
			NULL AS CHAVE_NFE,
			NULL AS PROTOCOLO_AUTORIZACAO_NFE,
			NULL AS PROTOCOLO_CANCELAMENTO_NFE,
			NULL AS DATA_AUTORIZACAO_NFE,
			GERAR_AUTOMATICO = 0,
			STATUS_NFE = 1,
			LOG_STATUS_NFE = '',
			MOTIVO_CANCELAMENTO_NFE = null,
			ITEM_NFE = 0,
			PRIORIZACAO = 0,
			REGISTRO_DPEC   = null,
			DATA_REGISTRO_DPEC  = null,
			TIPO_EMISSAO_NFE = 1,
			FIN_EMISSAO_NFE = 1,
			COD_MOTIVO_CANC = null,
			OBS_INTERESSE_FISCO  = null,
			DATA_CONTINGENCIA  = null,
			JUSTIFICATIVA_CONTINGENCIA  = null,
			UF_EMBARQUE_EXPORTACAO  = null,
			LOCAL_EMBARQUE_EXPORTACAO  = null,
			CFOP_CANCELAMENTO  = null,
			VALOR_DESPACHO = 0,
			VALOR_IMPOSTO_INCIDENCIA = 0,
			MPADRAO_VALOR_IMPOSTO_INCIDENCIA = 0,
			VEICULO_PLACA  = null,
			UF_PLACA_VEICULO  = null,
			INFORMACAO_COMPLEMENTAR  = null,
			MARCA_VOLUMES  = null,
			NUMERACAO_VOLUMES  = null,
			DATA_HORA_EMISSAO = getdate(),
			INDICA_PRESENCA_COMPRADOR = 9,
			LOCAL_DESPACHO_EXPORTACAO = null,
			UTC_DATA_AUTORIZACAO_NFE = null,
			UTC_DATA_SAIDA  = 3,
			UTC_EMISSAO  = 3,
			INDICA_ENDERECO_ENTREGA = 0,
			CONSTRUCAO_CIVIL = null,
			CADASTRO_CNO = null,
			INFO_PGTO = '90',
			TIPO_DOC_EXPORTACAO = null
	end try

	begin catch
		set @errmsg = 'CAPA - ' + ERROR_MESSAGE()
		rollback
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = @errmsg WHERE chave_dev = @chave_origem
		goto proximo
	end catch

	-- GERO OS PRODUTOS
	BEGIN TRY
		INSERT INTO FATURAMENTO_PROD
		(
			FILIAL,
			NF_SAIDA,
			SERIE_NF,
			PRODUTO,
			COR_PRODUTO,
			ITEM,
			PEDIDO,
			PEDIDO_PRODUTO,
			PEDIDO_COR,
			ENTREGA,
			CAIXA,
			IPI,
			ICMS,
			DESCONTO_ITEM,
			QTDE,
			PRECO,
			VALOR,
			PACKS,
			MATA_SALDO,
			F1,
			F2,
			F3,
			F4,
			F5,
			F6,
			F7,
			F8,
			F9,
			F10,
			F11,
			F12,
			F13,
			F14,
			F15,
			F16,
			F17,
			F18,
			F19,
			F20,
			F21,
			F22,
			F23,
			F24,
			F25,
			F26,
			F27,
			F28,
			F29,
			F30,
			F31,
			F32,
			F33,
			F34,
			F35,
			F36,
			F37,
			F38,
			F39,
			F40,
			F41,
			F42,
			F43,
			F44,
			F45,
			F46,
			F47,
			F48,
			FAIXA,
			ORIGEM,
			ROMANEIO,
			CUSTO_NA_DATA,
			TIMESTAMP,
			MOEDA,
			CAMBIO_NA_DATA,
			ORIGEM_EMB,
			DATA_PARA_TRANSFERENCIA,
			CODIGO_LOCAL_ENTREGA,
			COD_FILIAL_ESTOQUE,
			CODIGO_FISCAL_OPERACAO,
			CUSTO_NA_DATA_2,
			CUSTO_NA_DATA_3,
			CUSTO_NA_DATA_4,
			ITEM_IMPRESSAO,
			ITEM_IMPRESSAO_FATURA,
			ITEM_PEDIDO,
			ORDEM_PRODUCAO,
			PRECO_2,
			PRECO_3,
			PRECO_4,
			VALOR_DIFERENCA_GUIA_FATURA_ITEM,
			DESC_VENDA_CLIENTE,
			ID_MODIFICACAO,
			LICENCIADO_ROYALTIES,
			ID_VENDA_ENTREGA_FUTURA,
			ID_CEST_NCM
		)
		SELECT
			FILIAL = @filial_origem,
			NF_SAIDA = 'T99999',
			SERIE_NF = @serie_nf,
			PRODUTO = a.PRODUTO,
			COR_PRODUTO = a.COR_PRODUTO,
			ITEM = a.item,
			NULL AS PEDIDO,
			NULL AS PEDIDO_PRODUTO,
			NULL AS PEDIDO_COR,
			NULL AS ENTREGA,
			NULL AS CAIXA,
			IPI = 0,
			ICMS = 0,
			DESCONTO_ITEM = 0,
			QTDE = a.qtd,
			PRECO = a.PRECO1,
			VALOR = a.valor,
			PACKS = '',
			MATA_SALDO = 0,
			 F1 = A.F1, 
			 F2 = A.F2, 
			 F3 = A.F3, 
			 F4 = A.F4, 
			 F5 = A.F5, 
			 F6 = A.F6, 
			 F7 = A.F7, 
			 F8 = A.F8, 
			 F9 = A.F9, 
			 F10 = A.F10, 
			 F11 = A.F11, 
			 F12 = A.F12, 
			 F13 = A.F13, 
			 F14 = A.F14, 
			 F15 = A.F15, 
			 F16 = A.F16, 
			 F17 = A.F17, 
			 F18 = A.F18, 
			 F19 = A.F19, 
			 F20 = A.F20, 
			 F21 = A.F21, 
			 F22 = A.F22, 
			 F23 = A.F23, 
			 F24 = A.F24, 
			 F25 = A.F25, 
			 F26 = A.F26, 
			 F27 = A.F27, 
			 F28 = A.F28, 
			 F29 = A.F29, 
			 F30 = A.F30, 
			 F31 = A.F31, 
			 F32 = A.F32, 
			 F33 = A.F33, 
			 F34 = A.F34, 
			 F35 = A.F35, 
			 F36 = A.F36, 
			 F37 = A.F37, 
			 F38 = A.F38, 
			 F39 = A.F39, 
			 F40 = A.F40, 
			 F41 = A.F41, 
			 F42 = A.F42, 
			 F43 = A.F43, 
			 F44 = A.F44, 
			 F45 = A.F45, 
			 F46 = A.F46, 
			 F47 = A.F47, 
			 F48 = A.F48, 
 			FAIXA = '1',
			ORIGEM = 'E',
			NULL AS ROMANEIO,
			CUSTO_NA_DATA = 0,
			TIMESTAMP = DBO.FX_PRODUCAO_PRECO (a.PRECO1, 'T'),
			MOEDA = 'R$',
			CAMBIO_NA_DATA = 1,
			ORIGEM_EMB = null,
			DATA_PARA_TRANSFERENCIA = getdate(),
			CODIGO_LOCAL_ENTREGA = null,
			COD_FILIAL_ESTOQUE = @cod_filial,
			CODIGO_FISCAL_OPERACAO = @cfop,
			CUSTO_NA_DATA_2 = 0,
			CUSTO_NA_DATA_3 = 0,
			CUSTO_NA_DATA_4  = 0,
			ITEM_IMPRESSAO = a.item,
			ITEM_IMPRESSAO_FATURA = '',
			ITEM_PEDIDO = null,
			ORDEM_PRODUCAO  = null,
			PRECO_2  = 0,
			PRECO_3 = 0,
			PRECO_4 = 0,
			VALOR_DIFERENCA_GUIA_FATURA_ITEM = 0,
			DESC_VENDA_CLIENTE  = null,
			ID_MODIFICACAO  = null,
			LICENCIADO_ROYALTIES = 0,
			ID_VENDA_ENTREGA_FUTURA  = null,
			ID_CEST_NCM  = null
		FROM 
		(
			select right('0000' + rtrim(ltrim(cast(ROW_NUMBER() OVER(ORDER BY b.produto, b.cor_produto) as varchar(4)))),4) AS item,
					b.produto, b.cor_produto, c.PRECO1,
					sum(QUANTIDADE * c.PRECO1) as valor,
					sum(quantidade) as qtd,
					 F1 = SUM(CASE WHEN B.TAMANHO = 1 THEN A.QUANTIDADE ELSE 0 END), 
					 F2 = SUM(CASE WHEN B.TAMANHO = 2 THEN A.QUANTIDADE ELSE 0 END), 
					 F3 = SUM(CASE WHEN B.TAMANHO = 3 THEN A.QUANTIDADE ELSE 0 END), 
					 F4 = SUM(CASE WHEN B.TAMANHO = 4 THEN A.QUANTIDADE ELSE 0 END), 
					 F5 = SUM(CASE WHEN B.TAMANHO = 5 THEN A.QUANTIDADE ELSE 0 END), 
					 F6 = SUM(CASE WHEN B.TAMANHO = 6 THEN A.QUANTIDADE ELSE 0 END), 
					 F7 = SUM(CASE WHEN B.TAMANHO = 7 THEN A.QUANTIDADE ELSE 0 END), 
					 F8 = SUM(CASE WHEN B.TAMANHO = 8 THEN A.QUANTIDADE ELSE 0 END), 
					 F9 = SUM(CASE WHEN B.TAMANHO = 9 THEN A.QUANTIDADE ELSE 0 END), 
					 F10 = SUM(CASE WHEN B.TAMANHO = 10 THEN A.QUANTIDADE ELSE 0 END), 
					 F11 = SUM(CASE WHEN B.TAMANHO = 11 THEN A.QUANTIDADE ELSE 0 END), 
					 F12 = SUM(CASE WHEN B.TAMANHO = 12 THEN A.QUANTIDADE ELSE 0 END), 
					 F13 = SUM(CASE WHEN B.TAMANHO = 13 THEN A.QUANTIDADE ELSE 0 END), 
					 F14 = SUM(CASE WHEN B.TAMANHO = 14 THEN A.QUANTIDADE ELSE 0 END), 
					 F15 = SUM(CASE WHEN B.TAMANHO = 15 THEN A.QUANTIDADE ELSE 0 END), 
					 F16 = SUM(CASE WHEN B.TAMANHO = 16 THEN A.QUANTIDADE ELSE 0 END), 
					 F17 = SUM(CASE WHEN B.TAMANHO = 17 THEN A.QUANTIDADE ELSE 0 END), 
					 F18 = SUM(CASE WHEN B.TAMANHO = 18 THEN A.QUANTIDADE ELSE 0 END), 
					 F19 = SUM(CASE WHEN B.TAMANHO = 19 THEN A.QUANTIDADE ELSE 0 END), 
					 F20 = SUM(CASE WHEN B.TAMANHO = 20 THEN A.QUANTIDADE ELSE 0 END), 
					 F21 = SUM(CASE WHEN B.TAMANHO = 21 THEN A.QUANTIDADE ELSE 0 END), 
					 F22 = SUM(CASE WHEN B.TAMANHO = 22 THEN A.QUANTIDADE ELSE 0 END), 
					 F23 = SUM(CASE WHEN B.TAMANHO = 23 THEN A.QUANTIDADE ELSE 0 END), 
					 F24 = SUM(CASE WHEN B.TAMANHO = 24 THEN A.QUANTIDADE ELSE 0 END), 
					 F25 = SUM(CASE WHEN B.TAMANHO = 25 THEN A.QUANTIDADE ELSE 0 END), 
					 F26 = SUM(CASE WHEN B.TAMANHO = 26 THEN A.QUANTIDADE ELSE 0 END), 
					 F27 = SUM(CASE WHEN B.TAMANHO = 27 THEN A.QUANTIDADE ELSE 0 END), 
					 F28 = SUM(CASE WHEN B.TAMANHO = 28 THEN A.QUANTIDADE ELSE 0 END), 
					 F29 = SUM(CASE WHEN B.TAMANHO = 29 THEN A.QUANTIDADE ELSE 0 END), 
					 F30 = SUM(CASE WHEN B.TAMANHO = 30 THEN A.QUANTIDADE ELSE 0 END), 
					 F31 = SUM(CASE WHEN B.TAMANHO = 31 THEN A.QUANTIDADE ELSE 0 END), 
					 F32 = SUM(CASE WHEN B.TAMANHO = 32 THEN A.QUANTIDADE ELSE 0 END), 
					 F33 = SUM(CASE WHEN B.TAMANHO = 33 THEN A.QUANTIDADE ELSE 0 END), 
					 F34 = SUM(CASE WHEN B.TAMANHO = 34 THEN A.QUANTIDADE ELSE 0 END), 
					 F35 = SUM(CASE WHEN B.TAMANHO = 35 THEN A.QUANTIDADE ELSE 0 END), 
					 F36 = SUM(CASE WHEN B.TAMANHO = 36 THEN A.QUANTIDADE ELSE 0 END), 
					 F37 = SUM(CASE WHEN B.TAMANHO = 37 THEN A.QUANTIDADE ELSE 0 END), 
					 F38 = SUM(CASE WHEN B.TAMANHO = 38 THEN A.QUANTIDADE ELSE 0 END), 
					 F39 = SUM(CASE WHEN B.TAMANHO = 39 THEN A.QUANTIDADE ELSE 0 END), 
					 F40 = SUM(CASE WHEN B.TAMANHO = 40 THEN A.QUANTIDADE ELSE 0 END), 
					 F41 = SUM(CASE WHEN B.TAMANHO = 41 THEN A.QUANTIDADE ELSE 0 END), 
					 F42 = SUM(CASE WHEN B.TAMANHO = 42 THEN A.QUANTIDADE ELSE 0 END), 
					 F43 = SUM(CASE WHEN B.TAMANHO = 43 THEN A.QUANTIDADE ELSE 0 END), 
					 F44 = SUM(CASE WHEN B.TAMANHO = 44 THEN A.QUANTIDADE ELSE 0 END), 
					 F45 = SUM(CASE WHEN B.TAMANHO = 45 THEN A.QUANTIDADE ELSE 0 END), 
					 F46 = SUM(CASE WHEN B.TAMANHO = 46 THEN A.QUANTIDADE ELSE 0 END), 
					 F47 = SUM(CASE WHEN B.TAMANHO = 47 THEN A.QUANTIDADE ELSE 0 END), 
					 F48 = SUM(CASE WHEN B.TAMANHO = 48 THEN A.QUANTIDADE ELSE 0 END)
			from CGP_DEVOLUCAO_ECOM a
			left join PRODUTOS_BARRA b on a.COD_MERCADORIA = b.CODIGO_BARRA 
			left join PRODUTOS_PRECOS c on b.produto = c.produto and c.CODIGO_TAB_PRECO = '02'
			where ID_NFE_ORIGINAL = @chave_origem
			GROUP BY b.produto, b.cor_produto, c.PRECO1
		) a
	end try

	begin catch
		set @errmsg = 'PROD - ' + ERROR_MESSAGE()
		rollback
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = @errmsg WHERE chave_dev = @chave_origem
		goto proximo
	end catch
	
	      
	begin try
		UPDATE faturamento_sequenciais SET SEQUENCIAL =  right('000000000' + rtrim(ltrim(cast(cast(SEQUENCIAL as int) + 1 as char(12)))),9) WHERE SERIE_NF = @serie_nf and filial = @filial_origem

		SELECT @nf_numero = SEQUENCIAL FROM faturamento_sequenciais WHERE SERIE_NF = @serie_nf and filial = @filial_origem

		update FATURAMENTO set NF_SAIDA = @nf_numero where NF_SAIDA = 'T99999' AND FILIAL = @filial_origem and SERIE_NF = @serie_nf
	END TRY
	begin catch
		rollback
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'update nf_numero ' + ERROR_MESSAGE() WHERE chave_dev = @chave_origem
		goto proximo
	end catch
	
	--tabelas de apoio
	begin try
		EXEC dbo.LX_GERA_FATURAMENTO_ITEM  @EMISSAO, @EMISSAO, 'P', @filial_origem, @nf_numero,  @FILIAL_ORIGEM, @SERIE_NF, 1
		EXEC dbo.LX_GERA_IMPOSTOS_SAIDA  @FILiAL_ORIGEM, @nf_numero, @SERIE_NF, 1, 0, 1             
	end try
	begin catch
		rollback
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'TABELAS DE APOIO ' + ERROR_MESSAGE() WHERE chave_dev = @chave_origem
		goto proximo
	end catch

	--chave da nota
	begin try
		delete from #TEMP	
		
		INSERT INTO #TEMP EXEC DBO.LX_GERA_CHAVE_NFE_GENERICA @nf_numero, @SERIE_NF, @CNPJ, @CIDADE, @UF_FILIAL, @ANOMES, '55', 1, '4.00'                   
     
		SELECT @CHAVE_NFE = CHAVE_NF FROM #TEMP                       
                    
		UPDATE FATURAMENTO SET 
			CHAVE_NFE = @CHAVE_NFE, DATA_HORA_EMISSAO = GETDATE(),               
			 UTC_EMISSAO = 3, FIN_EMISSAO_NFE = 1, STATUS_NFE = 1               
		WHERE NF_SAIDA = @nf_numero AND SERIE_NF = @SERIE_NF and FILIAL = @filial_origem
	end try
	begin catch
		rollback
		update CSM_FILA_TRANSF set LOG_PROCESSAMENTO = 'CHAVE_NFE ' + ERROR_MESSAGE() WHERE chave_dev = @chave_origem
		goto proximo

	end catch

	commit

	update CSM_FILA_TRANSF set chave_transf = @CHAVE_NFE, LOG_PROCESSAMENTO = 'PROCESSO CONCLUIDO' WHERE chave_dev = @chave_origem

	--transito
	if isnull(@TRANSITO, '') = '.T.'
	begin
		exec LX_GERA_TRANSFERENCIA_AUTOMATICA @FILIAL=@filial_origem, @ROMANEIO_PRODUTO=@nf_numero,@FILIAL_DESTINO=@filial_destino,@SERIE_NF= @serie_nf, @ORIGEM='F', @EXCLUSAO='N'

		update LOJA_ENTRADAS 
		set ENTRADA_CONFERIDA = 1, ENTRADA_ENCERRADA = 1, DATA_ENTRADA_CONFERIDA = @emissao
		where FILIAL = @filial_destino and FILIAL_ORIGEM = @filial_origem and SERIE_NF_ENTRADA = @serie_nf and NUMERO_NF_TRANSFERENCIA = @nf_numero
	end

	goto proximo

	proximo:

	FETCH NEXT FROM cur_fila INTO @chave_origem
end

close cur_fila
deallocate cur_fila