insert into parametros 
(PARAMETRO, PENULT_ATUALIZACAO, VALOR_DEFAULT, ULT_ATUALIZACAO, VALOR_ATUAL, DESC_PARAMETRO, TIPO_DADO, RANGE_VALOR_ATUAL, GLOBAL, ESCOPO, POR_USUARIO_OK, DATA_PARA_TRANSFERENCIA, NOTA_PROGRAMADOR, PERMITE_POR_EMPRESA, ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, ENVIA_PARA_REPRESENTANTE, PERMITE_POR_REPRESENTANTE, PERMITE_ALTERAR_NO_REPRESENTANTE, APLICACAO)
select 
	PARAMETRO = 'CSM_TRANSITO_AUTOMATICO', 
	PENULT_ATUALIZACAO = CAST(GETDATE() AS DATE), 
	VALOR_DEFAULT = '.T.', 
	ULT_ATUALIZACAO = CAST(GETDATE() AS DATE),  
	VALOR_ATUAL = '.T.', 
	DESC_PARAMETRO = 'TRANSITO AUTOMATICO - PROCESSO TRANSFERENCIA TRIANGULAR', 
	TIPO_DADO = 'L', 
	RANGE_VALOR_ATUAL = '', 
	GLOBAL = 0, 
	ESCOPO = 0, 
	POR_USUARIO_OK = 0, 
	DATA_PARA_TRANSFERENCIA = GETDATE(), 
	NOTA_PROGRAMADOR = 'TRANSITO AUTOMATICO - PROCESSO TRANSFERENCIA TRIANGULAR', 
	PERMITE_POR_EMPRESA = 0, 
	ENVIA_PARA_LOJA = 0, 
	PERMITE_POR_LOJA = 0, 
	PERMITE_POR_TERMINAL = 0, 
	PERMITE_ALTERAR_NA_LOJA = 0, 
	PERMITE_ALTERAR_NO_TERMINAL = 0, 
	ENVIA_PARA_REPRESENTANTE = 0, 
	PERMITE_POR_REPRESENTANTE = 0, 
	PERMITE_ALTERAR_NO_REPRESENTANTE = 0, 
	APLICACAO = NULL


