USE [CAEDU]
GO

/****** Object:  View [dbo].[W_CTB_BALANCETE_SALDO_ANTERIOR]    Script Date: 16/10/2020 15:32:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--SELECT TABLE_NAME,COLUMN_NAME,DATA_TYPE,NUMERIC_PRECISION, NUMERIC_SCALE, CHARACTER_MAXIMUM_LENGTH 
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE COLUMN_NAME LIKE 'RATEIO_FILIAL'

CREATE TABLE CTB_BALANCETE_SALDO_ANTERIOR
(
EMPRESA INT NULL,
COD_FILIAL CHAR(6) NULL,
COD_MATRIZ_CONTABIL VARCHAR(25) NULL,
CENTRO_CUSTO VARCHAR(25) NULL,
TIPO_MOVIMENTO TINYINT NULL,
CONTA_CONTABIL VARCHAR(20),
DATA_SALDO DATETIME,
SALDO NUMERIC(14,2) NULL,
ID_GRUPO_CENTRO_CUSTO INT NULL,
SALDO_VALOR_FINANCEIRO_PADRAO NUMERIC(14,2) NULL,
COD_CLIFOR VARCHAR(6),
RATEIO_CENTRO_CUSTO VARCHAR(15) NULL,
RATEIO_FILIAL VARCHAR(15) NULL ,
CREDITO NUMERIC(14,2) NULL,
DEBITO NUMERIC(14,2) NULL
)
GO

ALTER VIEW [dbo].[W_CTB_BALANCETE_SALDO_ANTERIOR] AS

-- 09/10/2012 - ALEX BORTOTO - TP 3044766 - #1# - INCLUÍDO CAMPO LX_GRUPO_MOVIMENTO
-- 16/12/2010 - JOAO RICARDO - PERFORMANCE
SELECT   A.EMPRESA,
         A.COD_FILIAL,
         A.COD_MATRIZ_CONTABIL,
         A.CENTRO_CUSTO,
         A.TIPO_MOVIMENTO,
         A.CONTA_CONTABIL,
         A.DATA_SALDO,
         A.SALDO,
         A.ID_GRUPO_CENTRO_CUSTO,
         A.SALDO_VALOR_FINANCEIRO_PADRAO,
         A.COD_CLIFOR,
         MATRIZ_CONTABIL      = B.FILIAL,
         A.RATEIO_CENTRO_CUSTO,
         A.RATEIO_FILIAL,
         C.NOME_CLIFOR,
         C.RAZAO_SOCIAL,
         D.CODIGO_RESUMIDO,
         D.TIPO_CONTA,
         E.DESC_CONTA_TIPO,
         A.CREDITO,
         A.DEBITO,
         F.LX_GRUPO_MOVIMENTO --#1#
FROM CTB_BALANCETE_SALDO_ANTERIOR A
      JOIN FILIAIS B ON
         A.COD_MATRIZ_CONTABIL   = B.COD_FILIAL
      LEFT JOIN CADASTRO_CLI_FOR C ON
         A.COD_CLIFOR            = C.COD_CLIFOR
      JOIN CTB_CONTA_PLANO D ON
         A.CONTA_CONTABIL        = D.CONTA_CONTABIL
      JOIN CTB_CONTA_TIPO E ON
         D.TIPO_CONTA            = E.TIPO_CONTA   
      JOIN CTB_MOVIMENTO_TIPO F ON A.TIPO_MOVIMENTO = F.TIPO_MOVIMENTO --#1#







GO


